# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [72]:
import numpy as np
from numpy.random import randint as ri

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [7]:
mat1 = np.arange(12, 21).reshape(3,3)
mat2 = np.arange(2, 11).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat2/mat1)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 - 2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n",mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[12 13 14]
 [15 16 17]
 [18 19 20]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Addition
------------------
 [[14 16 18]
 [20 22 24]
 [26 28 30]]

Multiplication
------------------
 [[ 24  39  56]
 [ 75  96 119]
 [144 171 200]]

Division
------------------
 [[0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471]
 [0.44444444 0.47368421 0.5       ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[32 33 34]
 [35 36 37]
 [38 39 40]]

Addition of a scalar (100)
-------------------------
 [[112 113 114]
 [115 116 117]
 [118 119 120]]

Exponentiation, matrix cubed here
----------------------------------------
 [[1728 2197 2744]
 [3375 4096 4913]
 [5832 6859 8000]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[3.46410162 3.60555128 3.74165739]
 [3.87

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [46]:
mat1 = ri(9, size=(3, 3))
mat2 = ri(9, size=(3, 3))
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1[0:,0]), np.sum(mat1[0:,1]),np.sum(mat1[0:,2]))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1[0,0:]), np.sum(mat1[1,0:]),np.sum(mat1[2,0:]))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1[0,0:]), np.prod(mat1[1,0:]),np.prod(mat1[2,0:]))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2[0:,0]), np.prod(mat2[0:,1]),np.prod(mat2[0:,2]))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",mat1.mean())


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",mat1.std())


mat1 = ri(1,100, size=(3, 3))
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",mat1.std(),",",mat1.max())


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",pow(mat1.std(),2),",",mat1.max())


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1,axis = None))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[1 3 8]
 [4 4 4]
 [6 5 6]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[0 2 2]
 [0 7 1]
 [4 2 1]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 41

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 11 12 18

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 12 12 17

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 24 64 180

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 0 28 2

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.555555555555555

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 1.89215404065848

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [50]:
##Solution
mat1 = np.arange(12, 21).reshape(3,3)
print(mat1)
mat1 = mat1.reshape(9,1)
print(mat1)

[[12 13 14]
 [15 16 17]
 [18 19 20]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


### 4.Sort

In [67]:
A= np.random.randint(1,101,5) # Vector of random interegrs

print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)

print("\nHere is the sorted vector\n",'-'*50,"\n",sorted(A,key=int))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [15 24 83 33 23]

Here is the sorted vector
 -------------------------------------------------- 
 [15, 23, 24, 33, 83]


In [128]:
M = ri(1,26,size=(5,5)) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
M1= M
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=1)) # Default axis =1

print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M1,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[17 20  7  7 18]
 [ 3 25 23 11  2]
 [ 9 11  1  3  3]
 [14 22 22 19 13]
 [ 2  6 20  4  8]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 7  7 17 18 20]
 [ 2  3 11 23 25]
 [ 1  3  3  9 11]
 [13 14 19 22 22]
 [ 2  4  6  8 20]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 2  6  1  3  2]
 [ 3 11  7  4  3]
 [ 9 20 20  7  8]
 [14 22 22 11 13]
 [17 25 23 19 18]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [158]:
# Fill the following ***** with appropriate solution.
a=np.random.randint(1,100,10)
b=np.random.randint(1,100,10)
c=np.random.randint(1,100,10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", a.max())
print("Max of b:",a.max())


print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())




a: [52 35 49 44 47 17 82 25 89 41]
b: [43 94 70 79 20 60 56 94 21 63]
c: [15 29 13  9 26 34 27 17 95  3]
Max of a: 89
Max of b: 89
Max of a location: 8
Max of b location: 1
Max of c location: 8


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [166]:

mat1 = ri(1,10, size=(3, 3))
mat2 = ri(1,10, size=(3, 3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[2 1 5]
 [2 3 3]
 [6 1 2]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 6 4]
 [5 5 3]
 [1 9 4]]

Sq-root of 1st matrix using np
------------------
 [[1.41421356 1.         2.23606798]
 [1.41421356 1.73205081 1.73205081]
 [2.44948974 1.         1.41421356]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[  7.3890561    2.71828183 148.4131591 ]
 [  7.3890561   20.08553692  20.08553692]
 [403.42879349   2.71828183   7.3890561 ]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.30103    0.         0.69897   ]
 [0.30103    0.47712125 0.47712125]
 [0.77815125 0.         0.30103   ]]

Modulo reminder using np
 -------------------------------------------------- 
 [[2 1 1]
 [2 3 0]
 [0 1 2]]


### 7.Generating matrices from distributions

In [167]:

print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.12239147 0.0813653  0.89777357]
 [0.35044636 0.47790248 0.97841299]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-1.03571331  0.72341907  2.67943363]
 [ 0.57646716  0.45897488 -0.06260065]
 [-2.02280156  1.1591683   1.53972149]
 [-1.51927891 -0.72362327  0.39055064]]
Random integer vector: [23 44 61 82 61 49 12 86 36 56]

Random integer matrix
[[53 13 28  7]
 [39 78 86  2]
 [49  2 52 61]
 [23 48  7 28]]

20 samples drawn from a dice throw: [6 3 2 6 6 5 5 6 6 2 5 4 4 2 2 1 1 4 1 6]


### 8.Find the nearest value from a given number in an array using NumPy.

In [185]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element
a= ri(1,13,5)
print(a)
value = 10
print("index where the difference is minimum ", np.abs(a - value).argmin(),"the element is ", a[np.abs(a - value).argmin()])

[11  3 10  8  3]
index where the difference is minimum  2 the element is  10


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [259]:
print("[",end='')
for i in range(0,5,2):
   a  = np.array(np.linspace( 0, i, 3,dtype = int))
   print(a,end='')
print("]")
   
        




[[0 0 0][0 1 2][0 2 4]]
